"""removed is completed field from todo

Revision ID: 6c7bccfd5b1b
Revises: c5093fedf211
Create Date: 2025-05-29 19:59:42.702531

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c7bccfd5b1b"
down_revision: Union[str, None] = "c5093fedf211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "todo_items", ["todo_uid"])
    op.drop_column("todo_items", "is_completed")
    op.create_unique_constraint(None, "users", ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.add_column(
        "todo_items",
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "todo_items", type_="unique")
    # ### end Alembic commands ###
